spring:
  application:
    name: stay-focused-backend-monolith
  profiles:
    active: dev

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: false

logging:
  level:
    root: INFO
