spring:
  application:
    name: stay-focused-backend-monolith
  profiles:
    active: dev

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: false

logging:
  level:
    liquibase: off
    root: INFO

avatars:
  default:
    - "uri/my-repo/avatars/avatar1.png"
    - "uri/my-repo/avatars/avatar2.png"
    - "uri/my-repo/avatars/avatar3.png"
    - "uri/my-repo/avatars/avatar4.png"
    - "uri/my-repo/avatars/avatar5.png"
    -
  storage-type: CLOUDINARY

cloudinary:
  cloud-name: ${SF_MONO_CLOUDINARY_CLOUD_NAME}
  api-key: ${SF_MONO_CLOUDINARY_API_KEY}
  api-secret: ${SF_MONO_CLOUDINARY_API_SECRET}